experiment:
  name: null
  created_at: null

preprocessing:
  method: none
  resize_mode: padding
  image_size: 256
  normalization: imagenet
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
  params: null

model:
  model_type: efficientad
  image_size: 256
  batch_size: 16
  random_seed: 42
  threshold_method: percentile
  threshold_value: 95.0
  params: null
